# Generated by Django 4.2.6 on 2023-10-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseAnnouncement",
            fields=[
                (
                    "course_announcement_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("announcement_title", models.CharField(max_length=60)),
                ("announcement_text", models.TextField(max_length=400)),
                ("announcement_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
    ]
