# Generated by Django 4.2.6 on 2023-10-10 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_courses_course_term_and_more"),
        ("sampleclass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseannouncement",
            name="course_title",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.courses",
            ),
        ),
    ]
