# Generated by Django 4.2.6 on 2023-10-14 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sampleclass", "0002_coursemodules_modulesections"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modulesections",
            options={
                "verbose_name": "Module Section",
                "verbose_name_plural": "Module Sections",
            },
        ),
    ]
