# Generated by Django 4.2.6 on 2023-10-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sampleclass", "0003_alter_modulesections_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulesections",
            name="clickable_ind",
            field=models.BooleanField(default=False),
        ),
    ]
