# Generated by Django 4.2.6 on 2023-10-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sampleclass", "0005_courseassignments"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="media/assignments")),
                ("file_name", models.CharField(max_length=60)),
                ("file_upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sampleclass.courseassignments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment File",
                "verbose_name_plural": "Asssignment Files",
            },
        ),
    ]
