# Generated by Django 4.2.6 on 2023-10-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sampleclass", "0006_assignmentfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentfile",
            name="file",
            field=models.FileField(upload_to="assignments/"),
        ),
    ]
