# Generated by Django 4.2.6 on 2023-10-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sampleclass", "0008_assignmentuploadfile_delete_assignmentfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentuploadfile",
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
            },
        ),
    ]
