# Generated by Django 4.2.6 on 2023-10-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sampleclass", "0010_courseassignments_due_date_studentassignmentgrades"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassignments",
            name="due_time",
            field=models.TimeField(null=True),
        ),
    ]
