# Generated by Django 4.2.6 on 2023-10-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentaccount",
            name="year",
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
