# Generated by Django 4.2.6 on 2023-10-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_studentaccount_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentaccount",
            name="email",
        ),
    ]
