# Generated by Django 4.2.6 on 2023-10-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=60, unique=True)),
                ("course_term", models.DecimalField(decimal_places=0, max_digits=4)),
                ("exam_based", models.BooleanField(default=True)),
                ("project_based", models.BooleanField(default=False)),
                ("requires_lab", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
    ]
