# Generated by Django 4.2.6 on 2023-10-10 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_title",
                    models.CharField(max_length=60, null=True, unique=True),
                ),
                ("exam_based", models.BooleanField(default=True, null=True)),
                ("project_based", models.BooleanField(default=False, null=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="CourseSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_section",
                    models.CharField(max_length=60, null=True, unique=True),
                ),
                (
                    "course_term",
                    models.DecimalField(
                        choices=[
                            (2227, "Summer 2022-23"),
                            (2221, "Fall 2022-23"),
                            (2224, "Spring 2022-23"),
                            (2237, "Summer 2023-24"),
                            (2234, "Spring 2023-24"),
                            (2231, "Fall 2023-24"),
                        ],
                        decimal_places=0,
                        max_digits=4,
                    ),
                ),
                ("course_instructor", models.CharField(max_length=100, null=True)),
                (
                    "course_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.courses"
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Section",
                "verbose_name_plural": "Course Sections",
            },
        ),
        migrations.CreateModel(
            name="StudentCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, null=True)),
                (
                    "course_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.coursesections",
                    ),
                ),
                (
                    "course_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.courses"
                    ),
                ),
            ],
            options={
                "verbose_name": "Assigned Course",
                "verbose_name_plural": "Student Courses",
            },
        ),
    ]
