# Generated by Django 4.2.6 on 2023-10-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_courses_course_term"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_section", models.CharField(max_length=60, unique=True)),
                ("course_title", models.CharField(max_length=60, unique=True)),
                (
                    "course_term",
                    models.DecimalField(
                        choices=[
                            (2231, "Fall 2023-24"),
                            (2237, "Summer 2023-24"),
                            (2221, "Fall 2022-23"),
                            (2234, "Spring 2023-24"),
                            (2227, "Summer 2022-23"),
                            (2224, "Spring 2022-23"),
                        ],
                        decimal_places=0,
                        max_digits=4,
                    ),
                ),
                ("course_instructor", models.CharField(max_length=100)),
                ("course_location", models.CharField(max_length=100)),
                (
                    "course_open_seats",
                    models.DecimalField(decimal_places=0, max_digits=3),
                ),
                (
                    "course_taken_seats",
                    models.DecimalField(decimal_places=0, max_digits=3),
                ),
                (
                    "course_waitlist",
                    models.DecimalField(decimal_places=0, max_digits=2),
                ),
            ],
            options={
                "verbose_name": "Course Section",
                "verbose_name_plural": "Course Sections",
            },
        ),
        migrations.AlterField(
            model_name="courses",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2231, "Fall 2023-24"),
                    (2237, "Summer 2023-24"),
                    (2221, "Fall 2022-23"),
                    (2234, "Spring 2023-24"),
                    (2227, "Summer 2022-23"),
                    (2224, "Spring 2022-23"),
                ],
                decimal_places=0,
                max_digits=4,
            ),
        ),
    ]
