# Generated by Django 4.2.6 on 2023-10-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_studentcourses_course_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2221, "Fall 2022-23"),
                    (2227, "Summer 2022-23"),
                    (2231, "Fall 2023-24"),
                    (2237, "Summer 2023-24"),
                    (2234, "Spring 2023-24"),
                    (2224, "Spring 2022-23"),
                ],
                decimal_places=0,
                default=1,
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursesections",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2221, "Fall 2022-23"),
                    (2227, "Summer 2022-23"),
                    (2231, "Fall 2023-24"),
                    (2237, "Summer 2023-24"),
                    (2234, "Spring 2023-24"),
                    (2224, "Spring 2022-23"),
                ],
                decimal_places=0,
                default=1,
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentcourses",
            name="course_title",
            field=models.ForeignKey(
                default="LINEAR CIRCUITS",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.courses",
            ),
        ),
    ]
