# Generated by Django 4.2.6 on 2023-10-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_courses_course_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2237, "Summer 2023-24"),
                    (2221, "Fall 2022-23"),
                    (2231, "Fall 2023-24"),
                    (2234, "Spring 2023-24"),
                    (2224, "Spring 2022-23"),
                    (2227, "Summer 2022-23"),
                ],
                decimal_places=0,
                max_digits=4,
            ),
        ),
        migrations.CreateModel(
            name="StudentCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("course_section", models.CharField(max_length=60, unique=True)),
                (
                    "course_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.courses"
                    ),
                ),
            ],
            options={
                "verbose_name": "Assigned Course",
                "verbose_name_plural": "Student Courses",
            },
        ),
    ]
