# Generated by Django 4.2.6 on 2023-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_courses_course_term_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCourseGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=60)),
                ("course_grade", models.DecimalField(decimal_places=2, max_digits=5)),
                ("username", models.CharField(max_length=60, null=True)),
            ],
            options={
                "verbose_name": "Course Grade",
                "verbose_name_plural": "Course Grades",
            },
        ),
        migrations.AlterField(
            model_name="courses",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2227, "Summer 2022-23"),
                    (2224, "Spring 2022-23"),
                    (2221, "Fall 2022-23"),
                    (2237, "Summer 2023-24"),
                    (2234, "Spring 2023-24"),
                    (2231, "Fall 2023-24"),
                ],
                decimal_places=0,
                default=1,
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursesections",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2227, "Summer 2022-23"),
                    (2224, "Spring 2022-23"),
                    (2221, "Fall 2022-23"),
                    (2237, "Summer 2023-24"),
                    (2234, "Spring 2023-24"),
                    (2231, "Fall 2023-24"),
                ],
                decimal_places=0,
                default=1,
                max_digits=4,
                null=True,
            ),
        ),
    ]
