# Generated by Django 4.2.6 on 2023-11-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_studentcourses_course_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourses",
            name="course_nickname",
            field=models.CharField(
                default="<django.db.models.fields.related.ForeignKey>", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2224, "Spring 2022-23"),
                    (2237, "Summer 2023-24"),
                    (2227, "Summer 2022-23"),
                    (2234, "Spring 2023-24"),
                    (2221, "Fall 2022-23"),
                    (2231, "Fall 2023-24"),
                ],
                decimal_places=0,
                default=1,
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursesections",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2224, "Spring 2022-23"),
                    (2237, "Summer 2023-24"),
                    (2227, "Summer 2022-23"),
                    (2234, "Spring 2023-24"),
                    (2221, "Fall 2022-23"),
                    (2231, "Fall 2023-24"),
                ],
                decimal_places=0,
                default=1,
                max_digits=4,
                null=True,
            ),
        ),
    ]
