# Generated by Django 5.0 on 2023-12-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_alter_calendarevent_date_alter_courses_course_term_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2227, "Summer 2022-23"),
                    (2234, "Spring 2023-24"),
                    (2237, "Summer 2023-24"),
                    (2224, "Spring 2022-23"),
                    (2231, "Fall 2023-24"),
                    (2221, "Fall 2022-23"),
                ],
                decimal_places=0,
                default=1,
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursesections",
            name="course_term",
            field=models.DecimalField(
                choices=[
                    (2227, "Summer 2022-23"),
                    (2234, "Spring 2023-24"),
                    (2237, "Summer 2023-24"),
                    (2224, "Spring 2022-23"),
                    (2231, "Fall 2023-24"),
                    (2221, "Fall 2022-23"),
                ],
                decimal_places=0,
                default=1,
                max_digits=4,
                null=True,
            ),
        ),
    ]
