# Generated by Django 4.2.6 on 2023-10-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentCourseGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=60)),
                ("course_grade", models.DecimalField(decimal_places=2, max_digits=5)),
                ("username", models.CharField(max_length=60, null=True)),
            ],
            options={
                "verbose_name": "Course Grade",
                "verbose_name_plural": "Course Grades",
            },
        ),
    ]
