# Generated by Django 4.2.6 on 2023-10-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentcoursegrade",
            options={
                "verbose_name": "Course Grade",
                "verbose_name_plural": "Course Grades",
            },
        ),
    ]
