# Generated by Django 4.2.6 on 2023-10-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_alter_studentcoursegrade_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcoursegrade",
            name="username",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
